import { delay, http, HttpResponse, type HttpHandler } from 'msw';
import type {
  ApproveTicketsRequest,
  RejectTicketsRequest,
  RequestChangesRequest,
  ReviewDecisionResult,
  ReviewQueueItem,
} from '@/shared/api';
import { getGetReviewQueueMockHandler } from '@/shared/api/generated/review/review.msw';
import { MOCK_DELAY_MS, problem } from '@/shared/api/mocks';
import { parseSort } from '@/shared/lib';
import { departmentOf, seedReviewQueue } from './data';

/** The pending tickets of the mock backend. Decisions remove tickets from it, like the real queue. */
let queue = seedReviewQueue();

/** Back to the 58 starting tickets — called after every test (src/test/setup.ts). */
export function resetMockData(): void {
  queue = seedReviewQueue();
}

function inDepartment(url: URL): ReviewQueueItem[] {
  const departmentId = url.searchParams.get('departmentId');
  return departmentId ? queue.filter((t) => String(departmentOf(t)) === departmentId) : queue;
}

const SORT_VALUE: Record<string, (t: ReviewQueueItem) => string> = {
  sourceTicketId: (t) => t.sourceTicketId,
  title: (t) => t.title,
  project: (t) => t.project.name,
  authorName: (t) => t.authorName ?? '',
  enteredQueueAt: (t) => t.enteredQueueAt,
  reviewDueDate: (t) => t.reviewDueDate,
};

function sorted(tickets: ReviewQueueItem[], url: URL): ReviewQueueItem[] {
  const sort = parseSort(url.searchParams.get('sort')) ?? { field: 'reviewDueDate', order: 'asc' };
  const value = SORT_VALUE[sort.field] ?? SORT_VALUE.reviewDueDate;
  const direction = sort.order === 'asc' ? 1 : -1;
  return [...tickets].sort(
    (a, b) => (value ? value(a).localeCompare(value(b)) : 0) * direction || a.ticketId - b.ticketId,
  );
}

/** Applies a decision to the tickets still pending; 409 when none of them is pending any more. */
function decide(ticketIds: number[]) {
  const pending = new Set(queue.map((t) => t.ticketId));
  const decided = ticketIds.filter((id) => pending.has(id));
  if (decided.length === 0) return problem(409);
  queue = queue.filter((t) => !decided.includes(t.ticketId));
  return HttpResponse.json<ReviewDecisionResult>({ count: decided.length });
}

function blank(value: string | undefined): boolean {
  return !value || value.trim() === '';
}

export const handlers: HttpHandler[] = [
  // Typed handler generated by orval: the resolver must return a ReviewQueuePage.
  getGetReviewQueueMockHandler(async ({ request }) => {
    await delay(MOCK_DELAY_MS);
    const url = new URL(request.url);
    const size = Number(url.searchParams.get('size')) || 20;
    const page = Number(url.searchParams.get('page')) || 0;
    const all = sorted(inDepartment(url), url);
    return {
      content: all.slice(page * size, page * size + size),
      page: {
        size,
        number: page,
        totalElements: all.length,
        totalPages: Math.ceil(all.length / size),
      },
    };
  }),

  http.get('*/api/v1/review-queue/ticket-ids', ({ request }) =>
    HttpResponse.json({ ticketIds: inDepartment(new URL(request.url)).map((t) => t.ticketId) }),
  ),

  http.post('*/api/v1/reviews/approve', async ({ request }) => {
    await delay(MOCK_DELAY_MS);
    const body = (await request.json()) as ApproveTicketsRequest;
    return decide(body.ticketIds);
  }),

  http.post('*/api/v1/reviews/reject', async ({ request }) => {
    await delay(MOCK_DELAY_MS);
    const body = (await request.json()) as RejectTicketsRequest;
    if (blank(body.reason)) {
      return problem(400, 'MSG01', {
        fieldErrors: [{ field: 'reason', code: 'MSG01', params: { field_name: 'Reason' } }],
      });
    }
    return decide(body.ticketIds);
  }),

  http.post('*/api/v1/reviews/request-changes', async ({ request }) => {
    await delay(MOCK_DELAY_MS);
    const body = (await request.json()) as RequestChangesRequest;
    if (blank(body.comment)) {
      return problem(400, 'MSG01', {
        fieldErrors: [{ field: 'comment', code: 'MSG01', params: { field_name: 'Comment' } }],
      });
    }
    return decide(body.ticketIds);
  }),
];
